model:
  # TheSelective-A checkpoint (Atom-centric cross-attention)
  joint_ckpt: './checkpoints/theselective_a.pt'

  # Edge configuration for consistency with training
  cutoff_mode: knn
  knn: 32

sample:
  seed: 2021
  num_samples: 10
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior